apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: recommendation-delay
  namespace: boutique-istio
spec:
  hosts:
  - recommendationservice
  http:
  - fault:
      delay:
        fixedDelay: 2s        # atraso
        percentage: { value: 100 }
    route:
    - destination:
        host: recommendationservice
