apiVersion: batch/v1
kind: Job
metadata:
  name: loadgenerator-base
  namespace: perf-test
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: locust
        scenario: base
    spec:
      restartPolicy: OnFailure
      initContainers:
      - name: wait-frontend
        image: curlimages/curl:8.8.0
        command: ["/bin/sh","-c"]
        args: ['until curl -sSf http://frontend-external.boutique-base.svc.cluster.local/ >/dev/null; do sleep 4; done']
      - name: fix-permissions
        image: busybox
        command: ["sh", "-c", "chmod 777 /locust-results"]
        volumeMounts:
        - name: locust-results
          mountPath: /locust-results
      containers:
      - name: locust
        image: locust-boutique:local
        imagePullPolicy: Never
        env:
        - name: FRONTEND_ADDR
          value: "frontend-external.boutique-base.svc.cluster.local:80"
        - name: USERS
          value: "50"
        - name: RATE
          value: "5"
        - name: DURA
          value: "5m"
        command: ["/bin/sh","-c"]
        args:
        - |
          locust -f locustfile.py --headless \
          --host http://$FRONTEND_ADDR -u $USERS -r $RATE -t $DURA \
          --csv=/locust-results/base --exit-code-on-error 0 --exit-code-on-failure 0
        volumeMounts:
        - name: locust-results
          mountPath: /locust-results
      volumes:
      - name: locust-results
        emptyDir: {}
