# k6-smoke-testrun.yaml  – alvo: Online Boutique SEM Istio
apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  generateName: smoke-online-boutique-
  namespace: k6-operator          # onde o k6-operator está instalado
spec:
  parallelism: 4                  # 4 pods executores
  script:
    configMap:
      name: k6-smoke              # CM criado com o script smoke.js
      file: smoke.js
  arguments: --vus 50 --duration 1m -o experimental-prometheus-rw
  runner:
    env:
      # URL da aplicação dentro do cluster **SEM** Istio
      - name: BASE_URL
        value: http://frontend-external.online-boutique.svc.cluster.local
      # End-point do seu Prometheus dedicado
      - name: K6_PROMETHEUS_RW_SERVER_URL
        value: http://prom-lab-prometheus-server.monitoring.svc.cluster.local:80/api/v1/write

